### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by owen800q** [sdushantha/gitdir#6]
The link to directory that I want to download: [link](https://github.com/AvaloniaUI/Avalonia/tree/master/samples/ControlCatalog.Desktop)
![Screenshot from 2019-03-16 17-40-02](https://user-images.githubusercontent.com/19252045/54473442-8fc25680-4812-11e9-9da1-989c271b0c63.png)

env: ubuntu 16.04

**Comment by sdushantha** [comment]
Oh, I understand why thats happening. It is because you are trying to download a subdir. I dont think I tested the regex with that when I made `gitdir`.

 I will fix that when I have time, but at the moment I am really busy. Just so you know, you are more than welcome to send a PR :)

**Comment by IvanAdji** [comment]
I have the similar error:

`Traceback (most recent call last):
  File "gitdir.py", line 96, in <module>
    main()
  File "gitdir.py", line 48, in main
    r = urllib.request.urlretrieve(api_url)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

Is this the same problem situation or im doing something wrong. Plus the git repo is private that im trying to download it.

**Comment by sdushantha** [comment]
@owen800q @akivanctp 
This has been fixed now :)
Use the latest version
